apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rmpueu4uf-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rmpueu4uf-java-springboot-gitops